version: "3"
services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    env_file:
      - .env
    working_dir: /app
    # command: bash -c 'php bin/console server:run 0.0.0.0:8000'
  db:
    image: "mysql:5.7"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hola_test
      - MYSQL_USER=
      - MYSQL_PASSWORD=
    volumes:
      - ./data/:/var/lib/mysql
    ports:
      - "3307:3306"
