version: "3"
services:
    app:
        build: .
        ports:
          - "8000:8000"
        volumes:
          - .:/app
        env_file:
          - .env
        working_dir: /app
        networks:
          - backend
        depends_on:
          - db
        restart: on-failure
        links:
          - db
        environment:
          # Run "composer require symfony/orm-pack" to install and configure Doctrine ORM
          DATABASE_URL: mysql://root:root@db:3306/hola_test?serverVersion=5.7
    db:
        image: "mysql:5.7"
        restart: always
        environment:
          - MYSQL_ROOT_PASSWORD=root
          - MYSQL_DATABASE=hola_test
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
        networks:
          - backend
        volumes:
          - ./data/:/var/lib/mysql
        ports:
          - "3307:3306"
networks:
    backend:
        driver: bridge
